# Generated by Django 4.2.7 on 2023-12-02 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biddingapp', '0002_item_created_at_item_updated_at_vendor_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biddingapp.item')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biddingapp.vendor')),
            ],
        ),
    ]
